### ISSUE TITLE
read_line.to_i bug

### ISSUE THREAD

**Issue by orlando-labs** [socketry/protocol-http1#12] opened 2021-04-13 08:39 UTC
Hi, @ioquatix. There's a rare case when read_line for chunked body returns nil. Unfortunately, :to_i method of NilClass doesn't allow integer base as the parameter.

```
19.24s    error: Async::Task [oid=0xc1c] [pid=1446184] [2021-04-13 08:26:22 +0000]                                                                                                                                    
               |   ArgumentError: wrong number of arguments (given 1, expected 0)                                                                                                                                     
               |   → /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http1-0.13.2/lib/protocol/http1/body/chunked.rb:60 in `to_i'                                                                                        
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http1-0.13.2/lib/protocol/http1/body/chunked.rb:60 in `read'                                                                                        
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http-0.21.0/lib/protocol/http/body/readable.rb:86 in `each'                                                                                         
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http-0.21.0/lib/protocol/http/body/buffered.rb:47 in `for'                                                                                          
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http-0.21.0/lib/protocol/http/body/readable.rb:81 in `finish'                                                                                       
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/protocol-http-0.21.0/lib/protocol/http/body/reader.rb:52 in `finish'                                                                                         
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/async-http-0.54.1/lib/async/http/protocol/http1/server.rb:107 in `each'                                                                                      
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/async-http-0.54.1/lib/async/http/server.rb:53 in `accept'                                                                                                    
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/async-io-1.30.2/lib/async/io/server.rb:32 in `block in accept_each'                                                                                          
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/async-io-1.30.2/lib/async/io/socket.rb:73 in `block in accept'                                                                                               
               |     /usr/local/rvm/gems/ruby-3.0.0/gems/async-1.28.9/lib/async/task.rb:265 in `block in make_fiber'    
```

**Comment by ioquatix** [comment] 2021-04-14 21:58
Ah great. We should probably validate this then more explicitly. Care to make a PR?

**Comment by ioquatix** [comment] 2021-04-23 01:53
I looked at `to_i` and it looks like minor security concern, since `"12foobar".to_i == 12` which is not exactly great.

So, maybe we should consider `Integer(...)` in this case which fails with a more logical error.

**Comment by orlando-labs** [comment] 2021-04-23 07:12
To say more, there are [chunk extensions](https://tools.ietf.org/html/rfc7230#section-4.1.1). And line like '41 chunk_ext_key=chunk_ext_value' will be treated as integer 41 but the chunk extension info will be ignored at all.
Anyway, i'll look into more explicit and safe chunk header parsing.

**Comment by ioquatix** [comment] 2021-04-23 10:12
I did not know about chunk extensions, this is very fascinating. Is the semantics general to HTTP? I didn't see anything like this in HTTP/2 for example. The key point is, is this something we need to expose to the consumer of chunked body (even if it's a more specific interface).

**Comment by orlando-labs** [comment] 2021-04-23 10:22
Chunk extensions are specific to HTTP 1 only but widely used with various streaming services. At least I use them with async-http with monkey patches. 

Overall, they are like intermediate headers with multiple semicolon-separated key-value pairs where the values may be escaped strings, so just .split(';') isn't the right thing to parse these extensions.

I am using it via dedicated chunked body method :each_with_ext, which yields the chunk body and extensions hash to the consumer.

**Comment by ioquatix** [comment] 2021-04-23 21:02
I started investigating this and found https://stackoverflow.com/questions/62439557/are-chunk-extensions-supported-by-http-2-and-if-so-how/62441387#62441387 which leads to https://github.com/httpwg/http-core/issues/313

Even if we don't support it generally, as you say we could expose it in `protocol-http1` gem as a custom entry point to the body.

**Comment by ioquatix** [comment] 2021-04-23 21:11
Okay, it looks like it was merged: https://github.com/httpwg/http-core/pull/439

Therefore, we should probably consider how to handle this in the request/response abstraction.

Right now, trailers are only expected at the end. But now it seems like maybe they should be updated at any time reading the response body.

This is a pretty annoying abstraction to deal with because it impacts how we read chunks... we essentially have to be able to interleave data chunks and "header" data. It's not even clear that chunk extensions belong in the same namespace as headers.

**Comment by ioquatix** [comment] 2021-04-23 21:26
Here is the relevant section: https://github.com/httpwg/http-core/pull/439/files#diff-bf6c50d657b87bcff449520b39f314373d41822d808d7c87b3ebe2fc4df78863R2073

It seems like it needs incremental processing, i.e.

```ruby
body.each do |chunk|
  chunk.trailer # ... chunk extensions etc
end
```

The other option is to go all in with streams, i.e. the HTTP/2 model interleaving HEADER and DATA frames. But I'm not even sure if that's allowed.

The reason is, the model must be fully symmetric and able to forward/proxy requests/responses, etc. So, whatever model we have should be able to fully reproduce the correct underlying HTTP/1 or HTTP/2 protocol.

**Comment by ioquatix** [comment] 2021-04-23 21:33
It seems like we can't do this for HTTP/2 at least according to the current specification: https://github.com/httpwg/http-core/pull/439#issuecomment-825936561

**Comment by orlando-labs** [comment] 2021-04-24 18:10
They rather do not belong to the same space as headers and represent some metadata of the given chunk. 
So making a custom entry point for a chunked body in protocol-http1 gem will do its job it one needs these extensions, but it's a half-measure in the scope of the entire async-http gem as we can't keep the same interface across two http versions.

**Comment by ioquatix** [comment] 2021-04-24 22:44
> They rather do not belong to the same space as headers and represent some metadata of the given chunk.

I agree with your position however according to Roy Fielding who updated the RFC, it looks like these are considered intermediate trailer chunks.

I'd be happy with the following:

- Improvement to error handling of chunked parser.
- Interface for reading chunk extensions in `protocol-http1` and as you say, we don't expose it anywhere else.

**Comment by ioquatix** [comment] 2021-04-25 22:34
Okay, according to more discussion, this proposal was eventually remove/rejected. So, this is not part of the HTTP semantics.

**Comment by orlando-labs** [comment] 2021-04-26 14:11
It's slightly not clear. Will we do nothing with the both?

> - Improvement to error handling of chunked parser.
> - Interface for reading chunk extensions in protocol-http1 and as you say, we don't expose it anywhere else.

**Comment by ioquatix** [comment] 2021-04-27 06:59
Did we check that `curl` closing the request body is valid HTTP semantics?

I think we should do both those things I mentioned.

**Comment by ioquatix** [comment] 2021-05-08 04:17
I believe this issue is fixed in https://github.com/socketry/protocol-http1/commit/1d62fd69048397ce9cd51469e711422a0a2f3f60

If you have time to check it and report back that would be great!

**Comment by ioquatix** [comment] 2021-05-11 08:21
I'm sorry to hear that, hope you get better!

**Comment by orlando-labs** [comment] 2021-05-12 09:16
Hi, @ioquatix. I tested this a lot last day with clients that dropped their connections in a non-rfc way. It works pretty well. Raised EOFError clearly describes the behavior.

**Closed** 2021-05-13 04:21 UTC

**Comment by ioquatix** [comment] 2023-03-15 07:47
Do you think `chunked_body.each do |chunk, extensions|` should be a thing?

**Comment by orlando-labs** [comment] 2023-03-15 10:25
We've been using it this way via monkey patch for over a year now.
